# Generated by Django 4.1.2 on 2022-10-26 11:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("FSApp", "0002_books_delete_users"),
    ]

    operations = [
        migrations.AlterField(
            model_name="books", name="author", field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="books", name="img", field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="books", name="price", field=models.CharField(max_length=40),
        ),
        migrations.AlterField(
            model_name="books", name="title", field=models.CharField(max_length=40),
        ),
    ]
