# Generated by Django 4.1.1 on 2022-11-09 11:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("FSApp", "0005_cartbooks"),
    ]

    operations = [
        migrations.RenameField(
            model_name="cartbooks", old_name="cart", new_name="user",
        ),
    ]
