# Generated by Django 4.1.1 on 2022-11-09 13:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("FSApp", "0006_rename_cart_cartbooks_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cartbooks",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
